# 워크플로우 이름
name: Dev-Build Automation

# 1. 언제 실행할 것인가? (트리거 조건)
on:
  push:
    branches: ['main'] # main 브랜치에 git push 될 때

# 2. 무슨 작업을 할 것인가? eas build --plaform android --profile development
jobs:
  build_android_apk:
    name: Build Android Development APK
    type: build
    params:
      platform: android
      profile: development # eas.json의 development 프로필 사용