name: workflow for development

on:
  push:
    tags:
      - 'v*-dev'

jobs:
  build_development:
    name: building crossword development
    type: build
    params:
      platform: android
      profile: development 